/**
 * @file dynamic-nutrition-plan.entity.ts
 * @description Domain entity for a compensatory nutrition plan generated by the
 * backend from a plot's phenological-risk alert and monitoring indicators.
 */

export type NutritionInputStatus = 'Recommended' | 'Optional';
export type CertificationStatus = 'Pending' | 'Certified';

export interface NutritionInput {
  name: string;
  purpose: string;
  dosage: number;
  dosageUnit: string;
  status: NutritionInputStatus;
}

export interface NutritionApplicationWindow {
  startDate: string;
  endDate: string;
}

export interface NutritionRationale {
  summary: string;
  triggeringRiskLevel: string;
  ndviValue: number;
  temperatureAnomaly: number;
}

export interface NutritionApplication {
  applicationDate: string;
  applicationTime: string;
  appliedInputs: string[];
  doseConfirmation: string;
  fieldOperator: string;
  fieldNotes: string;
}

export interface DynamicNutritionPlanProperties {
  id?: number | null;
  userId?: number | null;
  plotId?: number | null;
  status?: string;
  inputs?: NutritionInput[];
  applicationWindow?: NutritionApplicationWindow | null;
  rationale?: NutritionRationale | null;
  generatedDate?: string;
  certificationStatus?: CertificationStatus;
  application?: NutritionApplication | null;
}

export class DynamicNutritionPlan {
  readonly id: number | null;
  readonly userId: number | null;
  readonly plotId: number | null;
  readonly status: string;
  readonly inputs: NutritionInput[];
  readonly applicationWindow: NutritionApplicationWindow | null;
  readonly rationale: NutritionRationale | null;
  readonly generatedDate: string;
  readonly certificationStatus: CertificationStatus;
  readonly application: NutritionApplication | null;

  constructor({
    id = null,
    userId = null,
    plotId = null,
    status = 'Recommended',
    inputs = [],
    applicationWindow = null,
    rationale = null,
    generatedDate = '',
    certificationStatus = 'Pending',
    application = null,
  }: DynamicNutritionPlanProperties = {}) {
    this.id = id;
    this.userId = userId;
    this.plotId = plotId;
    this.status = status;
    this.inputs = inputs;
    this.applicationWindow = applicationWindow;
    this.rationale = rationale;
    this.generatedDate = generatedDate;
    this.certificationStatus = certificationStatus;
    this.application = application;
  }

  /** Human plan code, e.g. "DN-042". */
  get planCode(): string {
    return `DN-${String(this.id ?? 0).padStart(3, '0')}`;
  }

  get isCertified(): boolean {
    return this.certificationStatus === 'Certified' || this.application !== null;
  }

  /** Recommended (non-optional) input names, prefilled in the Certify form. */
  get recommendedInputNames(): string[] {
    return this.inputs.filter((input) => input.status === 'Recommended').map((input) => input.name);
  }
}
